config/routes.rb
Rails.application.routes.draw do
  resources :verifcns
  resources :outils

resources :cens do
	  collection do
		  get 'get_heure_tot'
	  end
  end
  resources :bon_lancements do 
	  collection do
		  get 'get_type_visite'
	  end
  end
   resources :maint_previs  do
	  collection do
		  get 'recalcul'
	  end
  end

  resources :equipement_vaut_pours

  resources :vaut_pours

  resources :est_monte_surs do 
	  collection do
		  get 'val_pot'
	  end
  end
  

  resources :equipements

  resources :visite_equipements do 
	  collection do
		get  'get_visite_equ'
		get 'get_type_visite'
	end
end

  resources :exec_cn_equipements do 
	  collection do
		get  'cn_type_equipement'
	end
end
  
  

  resources :cn_equipements

  resources :potentiel_equipements

  resources :visite_protocolaire_equipements

  resources :type_equipements

  resources :modif_repars

  resources :visite_machines do
	  collection do
		  get 'get_type_visite'
		  get 'get_type_machine'
	  end
  end
  

  resources :exec_cn_machines do
	collection do
		get 'cn_typemachine'
	end
end

  resources :doc_divers do
	  collection do
		  get 'envoi_doc'
		  post 'save_doc'
		  post 'suppr_doc'
	  end
  end
  
  resources :potentiel_machines 
  
  resources :type_potentiels  do
	  collection do
		  get 'get_unitee'
	  end
  end

  resources :cn_machines

  resources :visite_protocolaires

  resources :type_machines

  resources :machines

  resources :carnets

  resources :page_acces

  resources :personnes

resources :personnes do
end

resources :appli do
  collection do
    get 'login'
    post 'login'
    post 'create_new'
    get 'logout'
    get 'welcome'
    get 'bandeau_gauche'
  end
end
resources :machines do
end

  root :to => 'machines#index'
end

app/models/cen.rb
class Cen  < ActiveRecord::Base
	belongs_to:machine, :foreign_key =>:id_machine
	belongs_to:personne, :foreign_key =>:id_personne
	validates :id_machine , presence: { message: "La machine n'est pas définie" }
	validates :id_personne , presence:  { message: "Le PEN n'est pas défini" }
	validates :num_cen , presence:  { message: "Le numéro du CEN n'est pas défini" }
	validates :deliv , presence:  { message: "La date d'examen n'est pas défini" }
	validates :expire , presence:  { message: "La date de validité n'est pas défini" }
end

app/controllers/cens_controller.rb
class CensController < ApplicationController
	include ApplicationHelper
  before_action :page_def
  before_action :set_cen, only: %i[ show edit update destroy ]
  before_action :page_acc 
  helper_method :val_pot
  protect_from_forgery  except: [:get_heure_tot]
  # GET /cens or /cens.json
  def index
    @cens = Cen.all.order(num_cen: :desc)
  end

  # GET /cens/1 or /cens/1.json
  def show
	  respond_to do |format|
		format.html {}
		format.docx {
		#format docx
		#teste cen ou AC15
		if (params[:type_rapport] == "cen") then
			#CEN
			#on ouvre le template
			doc = Doc.new("#{Rails.root}/app/reports/15c.docx", "#{Rails.root}/tmp/docx/")
			# on modifie 
			doc.replace("$num_cen$", @cen.num_cen)
			doc.replace("$const$", @cen.machine.type_machine.Nom_constructeur.upcase)
			doc.replace("$modele$", @cen.machine.type_machine.type_machine)
		        doc.replace("$immat$", @cen.machine.Immatriculation)
			doc.replace("$num_serie$", @cen.machine.num_serie)
			doc.replace("$deliv$", @cen.deliv.strftime('%d.%m.%Y'))
			doc.replace("$exp$", @cen.expire.strftime('%d.%m.%Y'))
			doc.replace("$heure_tot$", @cen.heure_cellule)
			doc.replace("$nom$",@cen.personne.Nom.upcase + " " +@cen.personne.prenom[0].upcase)
			doc.replace("$poet$",@cen.personne.autor)

		      # Write the document back to a temporary file
		       tmp_file = Tempfile.new('word_template', "#{Rails.root}/tmp/")
		       tmp_file.close
		      doc.commit(tmp_file.path)
		      # Respond to the request by sending the temp file
		      send_file tmp_file.path, filename: "cen#{@cen.num_cen.to_s}.docx", disposition: 'attachment'
					
					#on envoi
		elsif (params[:type_rapport] == "ac158d") then
			doc = Doc.new("#{Rails.root}/app/reports/ac158e_FR.docx", "#{Rails.root}/tmp")
			# on modifie 
			doc.replace("$immat$", @cen.machine.Immatriculation)
			doc.replace("$model$", @cen.machine.type_machine.type_machine)
		        doc.replace("$num_serie$", @cen.machine.num_serie)
			doc.replace("$heure_cellule$", @cen.heure_cellule)
			#moteur
			moteurs=Equipement.joins(:est_monte_sur,:type_equipement).where(type_equipements: {moteur: true },est_monte_surs: {idmachine: @cen.id_machine ,date_retrait: nil})
			if (moteurs.length >0) then
				# c'est appareil avce moteur
					doc.replace("$moteur_typ$", moteurs[0].type_equipement.nom_constructeur + moteurs[0].type_equipement.type_equipement)
					doc.replace("$mot_serie$",  moteurs[0].num_serie)
					pot_init=PotentielMontage.where(idtype_potentiel: 4,idest_monte_sur: moteurs[0].est_monte_sur[0].id)
					potinit_val=pot_init[0].valeur_machine_jour_montage
					
				else
					#planeur pur
					doc.replace("$moteur_typ$","/")
					doc.replace("$mot_serie$",  "/")
				end
			#helice
			moteurs=Equipement.joins(:est_monte_sur,:type_equipement).where(type_equipements: {helice: true },est_monte_surs: {idmachine: @cen.id_machine ,date_retrait: nil})
			if (moteurs.length >0) then
				# c'est appareil avce moteur
					doc.replace("$hel$", moteurs[0].type_equipement.nom_constructeur + moteurs[0].type_equipement.type_equipement)
					doc.replace("$helice_serie$",  moteurs[0].num_serie)
					pot_init=PotentielMontage.where(idtype_potentiel: 4,idest_monte_sur: moteurs[0].est_monte_sur[0].id)
					potinit_val=pot_init[0].valeur_machine_jour_montage
					
				else
					#planeur pur
					doc.replace("$hel$","/")
					doc.replace("$helice_serie$",  "/")
				end
			
			if (@cen.nuissance_sonore) then
					doc.replace("$nui_oui$", "\u2612".encode('utf-8'))
					doc.replace("$nui_non$", "\u2610".encode('utf-8'))
				else
					doc.replace("$nui_oui$", "\u2610".encode('utf-8'))
					doc.replace("$nui_non$", "\u2612".encode('utf-8'))
				end
			doc.replace("$date$", @cen.deliv.strftime('%d.%m.%Y'))
			nom = @cen.personne.Nom.upcase + " " +@cen.personne.prenom[0].upcase
			doc.replace("$nom$", nom)
			

		     # Write the document back to a temporary file
		       tmp_file = Tempfile.new('word_template', "#{Rails.root}/tmp/")
		       tmp_file.close
		      doc.commit(tmp_file.path)
		      # Respond to the request by sending the temp file
		      send_file tmp_file.path, filename: "ac158_#{@cen.num_cen.to_s}.docx", disposition: 'attachment'
					
			#on envoi
		else
			#annexe V
			doc = Doc.new("#{Rails.root}/app/reports/examen_nav_CAB.docx", "#{Rails.root}/tmp")
			# on modifie 
			doc.replace("$const$", @cen.machine.type_machine.Nom_constructeur.upcase)
			doc.replace("$immat$", @cen.machine.Immatriculation,true)
			doc.replace("$modele$", @cen.machine.type_machine.type_machine)
		        doc.replace("$num_serie$", @cen.machine.num_serie)
			doc.replace("$heure_cellule$", @cen.heure_cellule)
			doc.replace("$heure_tot$", @cen.heure_cellule)
			#gestion des PE
			#moteur
			moteurs=Equipement.joins(:est_monte_sur,:type_equipement).where(type_equipements: {moteur: true },est_monte_surs: {idmachine: @cen.id_machine ,date_retrait: nil})
			if (moteurs.length >0) then
				# c'est appareil avce moteur
					doc.replace("$moteur_cons$", moteurs[0].type_equipement.nom_constructeur)
					doc.replace("$moteur_typ$", moteurs[0].type_equipement.nom_constructeur + moteurs[0].type_equipement.type_equipement)
					doc.replace("$mot_serie$",  moteurs[0].num_serie)
					pot_init=PotentielMontage.where(idtype_potentiel: 4,idest_monte_sur: moteurs[0].est_monte_sur[0].id)
					potinit_val=pot_init[0].valeur_machine_jour_montage
					
				else
					#planeur pur
					doc.replace("$moteur_cons$","/")
					doc.replace("$moteur_typ$","/")
					doc.replace("$mot_serie$",  "/")
				end
			#helice
			moteurs=Equipement.joins(:est_monte_sur,:type_equipement).where(type_equipements: {helice: true },est_monte_surs: {idmachine: @cen.id_machine ,date_retrait: nil})
			if (moteurs.length >0) then
				# c'est appareil avce moteur
					doc.replace("$helice_cons$", moteurs[0].type_equipement.nom_constructeur)
					doc.replace("$helice_model$", moteurs[0].type_equipement.type_equipement)
					doc.replace("$helice_serie$", moteurs[0].num_serie)
					pot_init=PotentielMontage.where(idtype_potentiel: 4,idest_monte_sur: moteurs[0].est_monte_sur[0].id)
					potinit_val=pot_init[0].valeur_machine_jour_montage
					
				else
					#planeur pur
					doc.replace("$helice_cons$","/")
					doc.replace("$helice_model$","/")
					doc.replace("$helice_serie$",  "/")
				end
			
			if (@cen.nuissance_sonore) then
					doc.replace("$nui_oui$", "\u2612".encode('utf-8'))
				else
					doc.replace("$nui_oui$", "\u2610".encode('utf-8'))
				end
			doc.replace("$pe$",@cen.machine.type_machine.ref_manuel_entretien)
			doc.replace("$rev$",@cen.machine.type_machine.revision)
			if (@cen.machine.type_machine.date_revision.nil?) then doc.replace("$pe_rev$","") else doc.replace("$pe_rev$",@cen.machine.type_machine.date_revision.strftime('%d.%m.%Y'))end
			if (@cen.machine.type_machine.date_approb.nil?) then doc.replace("$approb$","") else doc.replace("$approb$",@cen.machine.type_machine.date_approb.strftime('%d.%m.%Y')) end 
			doc.replace("$date$", @cen.deliv.strftime('%d.%m.%Y'))
			doc.replace("$deliv$", @cen.deliv.strftime('%d.%m.%Y'),true)
			nom = @cen.personne.Nom.upcase + " " +@cen.personne.prenom[0].upcase
			doc.replace("$nom$", nom)
			

		     # Write the document back to a temporary file
		       tmp_file = Tempfile.new('word_template', "#{Rails.root}/tmp/")
		       tmp_file.close
		      doc.commit(tmp_file.path)
		      # Respond to the request by sending the temp file
		      send_file tmp_file.path, filename: "annexeV_#{@cen.num_cen.to_s}.docx", disposition: 'attachment'
		end
		
		}
	end
	
  end

  # GET /cens/new
  def new
    @date_1= Date.today.strftime('%d/%m/%Y')
    @cen = Cen.new
  end

  # GET /cens/1/edit
  def edit
	  @date1=@cen.deliv.strftime('%d/%m/%Y')
	  @date2=@cen.expire.strftime('%d/%m/%Y')
  end

  # POST /cens or /cens.json
  def create
    @cen = Cen.new(cen_params)

    respond_to do |format|
      if @cen.save
        format.html { redirect_to @cen, notice: "Cen was successfully created." }
        format.json { render :show, status: :created, location: @cen }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cen.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cens/1 or /cens/1.json
  def update
    respond_to do |format|
      if @cen.update(cen_params)
        format.html { redirect_to @cen, notice: "Cen was successfully updated." }
        format.json { render :show, status: :ok, location: @cen }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cen.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cens/1 or /cens/1.json
  def destroy
    @cen.destroy
    respond_to do |format|
      format.html { redirect_to cens_url, notice: "Cen was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  def get_heure_tot
	        releve=Carnet.liste_machine_carnet(params[:id_machine])
		@heure_tot=pres_val(releve["heure_de_vol"],"Heure de vol")
	  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cen
      @cen = Cen.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cen_params
      params.fetch(:cen, {}).permit(:num_cen, :deliv,:expire,:heure_cellule,:id_machine,:id_personne,:nuissance_sonore)
    end
end

app/helpers/cens_helper.rb
module CensHelper
end

app/views/cens/_form.html.erb
<%= form_for(@cen) do |f| %>
  <% if cen.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cen.errors.count, "error") %> prohibited this cen from being saved:</h2>

      <ul>
        <% cen.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<h2> Numéro :<%= f.text_field "num_cen", :size => 20 %>
	<label for="machine">Machine :<%=  f.select "id_machine", Machine.all.collect {|p| [ p.Immatriculation, p.id ] },{:include_blank=> 'None'} %></h2>
 <p>
 <table  border=1 width=80%>
  <tr>
	<td>date de délivrance :<%= f.text_field  "deliv",{:value=>@date1, :class =>"date_saisie",:size => 10} %></td>
	<td>date d'expiration    :<%= f.text_field  "expire",{:value=>@date2, :class =>"date_saisie",:size => 10} %></td>
  </tr>
  <tr>
  <td>examen fait par : <%= f.select "id_personne", Personne.all.collect {|p| [ p.Nom, p.id ] },{:include_blank=> 'None'}%></td>
  <td>certif nuissance :<%=  f.check_box "nuissance_sonore",{} %>
		 </td>
  </tr>
  <tr>
  <td><div class="heure_cell"> Heure cellule : <%= f.text_field "heure_cellule", :size => 20 %></div> </td>
  <td></td>
  </tr>
  </table>
  <div class="actions">
    <%= f.submit "sauvegarder" %>
  </div>
<% end %>

app/views/cens/edit.html.erb
<h1>Modifier un CEN</h1>

<%= render 'form', cen: @cen %>

<%= link_to 'Détail', @cen %> |
<%= link_to 'retour à la liste', cens_path %>

app/views/cens/get_heure_tot.js.erb
$('#heure_cell').html("<input size="20" type="text" name="cen[heure_cellule]" id="cen_heure_cellule" value= "<%=@heure_tot %>"/>");

app/views/cens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>liste des Certificats de navigabilté </h1>
<%= link_to 'nouveau certificat', new_cen_path %>
<p><%= link_to "liste des CEN", {controller: "machines", action: "index",:format => :pdf}%> </p>
<table border=1 width 40%>
  <thead>
    <tr>
      <th>Référence</th>
      <th>Machine</th>
      <th>Signataire</th>
      <th>date de délivrance</th>
      <th>date de validité</th>
      <th>Mod</th>
      <th>Supp</th>
      <th>Imp cen</th>
      <th>Imp ac158b</th>
      <th>Imp annexe V</th>
    </tr>
  </thead>

  <tbody
  <%@cens.each do |cen| %>
      <tr>
	<td><%=link_to cen.num_cen,cen%></td>
	<td><%=cen.machine.Immatriculation%></td>
	<td><%=cen.personne.Nom%>  <%=cen.personne.prenom%></td>
	<td><%= cen.deliv.strftime('%d/%m/%Y')%></td>
	<td><%= cen.expire.strftime('%d/%m/%Y')%></td>
	<td><%= mod_link edit_cen_path(cen) %></td>
        <td><%= del_link cen %></td>
	<td><%= print_link cen_path(cen, :format => 'docx',:type_rapport=>"cen") %></td>
	<td><%= print_link cen_path(cen, :format => 'docx',:type_rapport=>"ac158d") %></td>
	<td><%= print_link cen_path(cen, :format => 'docx',:type_rapport=>"annexeV") %></td>
      </tr>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'nouveau certificat', new_cen_path %>

app/views/cens/new.html.erb
<h1>Nouveau CEN</h1>

<%= render 'form', cen: @cen %>

<%= link_to 'Retour à liste', cens_path %>

app/views/cens/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Cen numéro <%=@cen.num_cen%></h1>
<h1><%=@cen.machine.type_machine.type_machine%> <%=@cen.machine.Immatriculation%></h1>

<h2> détails</h2>
date de délivrance          : <%= @cen.deliv.strftime('%d/%m/%Y')%></p>
Heure Cellule à délivrance:<%= @cen.heure_cellule %></p>
Date d'exipration            : <%= @cen.expire.strftime('%d/%m/%Y')%></p>
Soumis Nuissance sonore : <%= if @cen.nuissance_sonore then image_tag "case_a_cocher.gif" else image_tag "case_cocher_vide.jpg" end %></p>
rédacteur			  : <%=@cen.personne.Nom + @cen.personne.prenom%></p>

<%= link_to 'Retour à liste', cens_path %>